### ISSUE TITLE
How to do grid search like LIBSVM?

### ISSUE THREAD

**Issue by zccyman** [zeyiwen/thundersvm#27]

**Comment by zeyiwen** [comment]
Current grid search is not supported in ThunderSVM. We are working on adding this functionality to ThunderSVM. Stay tuned.

You are more than welcome to help improve ThunderSVM :)

**Comment by shijiashuai** [comment]
Since ThunderSVM supports cross-validation. You can write a simple script like this one.
```bash
#!/usr/bin/bash
DATASET=$1
OPTIONS=
N_FOLD=5
for c in 1 3 10 30 100
do
  for g in 0.1 0.3 1 3 10
    do
      bin/thundersvm-train -c ${c} -g ${g} -v ${N_FOLD} ${OPTIONS} ${DATASET}
    done
done
```
then run `sh grid.py [dataset]` will print accuracy score for each parameter pair. And you can find the one with max score. The script is very simple, you may modify it to meet your needs.

Indeed, ThunderSVM supports the same command line parameters like LIBSVM. So the script `grid.py` in LIBSVM can be used for ThunderSVM with minor modifications.

**Comment by zccyman** [comment]
@shijiashuai  thanks!

**Comment by zeyiwen** [comment]
I've added this question and answer to [FAQ](http://thundersvm.readthedocs.io/en/latest/faq.html) page.
