### ISSUE TITLE
CPU version compilation error on Mac. Any paper about thundersvm?

### ISSUE THREAD

**Issue by xuehuanran** [zeyiwen/thundersvm#29]
Is there any paper about thundersvm? And I use eigen to compile the code without cuda, but there is always error in the Make process.

**Comment by shijiashuai** [comment]
You can paste the error message here. Then I can help you find what's wrong :)

**Comment by xuehuanran** [comment]
This is the error message. Thank you!
[error_message.txt](https://github.com/zeyiwen/thundersvm/files/1517794/error_message.txt)

**Comment by bingshenghe** [comment]
you can refer more details in this overview paper:
http://www.comp.nus.edu.sg/~hebs/pub/thundersvm.pdf

**Comment by zccyman** [comment]
in windows, I use cmake to generate the thundersvm Visual Studio Project, but some error appeared.can you any suggestion?

**Comment by shijiashuai** [comment]
It seems that your operating system is macOS, whose default c compiler is clang instead of gcc. 

ThunderSVM needs OpenMP that is not supported by clang. If you want to compile ThunderSVM on your mac, I recommend you install gcc.

```bash
brew install gcc
```
If you don't have Homebrew, [here](https://brew.sh/) is its website.

Then you can specify gcc as the compiler of cmake. (`[path_to_g++]` is typically `g++-7` but may be different in your system)

```bash
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILIER=[path_to_g++] -DCMAKE_C_COMPILER=[path_to_gcc] -DUSE_CUDA=OFF -DUSE_EIGEN=ON ..
make -j
```
Some other problems have been fixed in the lateset commit.

**Comment by xuehuanran** [comment]
It really works after updating the latest commit. Thank you!
