### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [zeyiwen/thundersvm#31]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/zeyiwen/thundersvm/blob/1a880a18c15ea3ee650e2adb0c11e61cfbcffee2/src/thundersvm/thundersvm-train.cpp#L16 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by shijiashuai** [comment]
Thanks for your suggestion. I have read the links your mentioned, realizing it would be useful for users to get an error message instead of an exception. I've tried to add some try-catch statements in main(). You are more than welcome to create a pull request it if you find that it can be improved :D

**Comment by bingshenghe** [comment]
hi elfring: thanks for your input. let us know if you observe other things to improve.
