### ISSUE TITLE
performance issue when I use cross-validation

### ISSUE THREAD

**Issue by limin2015** [zeyiwen/thundersvm#76]
When I use 5-fold cross-validation to run the a9a dataset (that is 5 times running of svm trainning). It is observed that the execution time of the first one is much slower than the left (525ms, 249ms, 254ms, 257ms, 261ms, respectively )? Do you know why? Is there special performance optimization for  cross-validation?

**Comment by zeyiwen** [comment]
In this version, we haven't optimized the cross-validation, although it could be. This first round is slower may be because the first training problem is more difficult than the rest. You may take a look to check if the total number of iterations of the first round is much larger than the others. 

You may also share the hyper-parameters that you used, and we should be able to identify if the code has bugs or that is just normal.

**Comment by limin2015** [comment]
1. The hyper-parameters are as follows : cost = 4, gamma= 0.5 with RBF kernel; dataset is a9a (nSamples=32561).
2. The global iterations of the five rounds are as follows: 146, 141, 142, 142, 145. As you can see, the first value is not much larger than the others.

**Comment by zeyiwen** [comment]
I've tried to reproduce the problem, but didn't see any abnormal. The difference may be due to the inaccuracy of measuring elapsed time, or your thundersvm progrom was disturbed by other processes.

**Comment by limin2015** [comment]
I use get_time_of_day() to measure time. And I only run the thundersvm program at the same time on my machine. Thanks for your help. I will check it again.
